### ISSUE TITLE
이건 뭔가요?

### ISSUE THREAD

**Issue by Kerry-Cho** [bemoregt/pwwMaskR-CNNMaskEditor#1]
라벨링 툴인가요?

**Comment by bemoregt** [comment]
Hi, @kerry-Cho 

Yes, It is Mask editor for Mask R-CNN with PASCAL VOC.

But version 0.1. 

@bemoregt .

**Comment by bemoregt** [comment]
@kerry-Cho 

근데 저를 아시는 분인가요?

한글로 답을 다신걸 보면...

**Comment by Kerry-Cho** [comment]
@bemoregt  네이버 카페...
